import type { ITechStack } from '@/types';
import {
	SiAlpinedotjs,
	SiAlpinedotjsHex,
	SiAntdesign,
	SiAntdesignHex,
	SiChakraui,
	SiChakrauiHex,
	SiDjango,
	SiDjangoHex,
	SiDocker,
	SiDockerHex,
	SiExpress,
	SiFirebase,
	SiFirebaseHex,
	SiFlask,
	SiFlaskHex,
	SiGo,
	SiGoHex,
	SiGraphql,
	SiGraphqlHex,
	SiJavascript,
	SiJavascriptHex,
	SiLinux,
	SiLinuxHex,
	SiMongodb,
	SiMongodbHex,
	SiMui,
	SiMuiHex,
	SiNestjs,
	SiNestjsHex,
	SiNextdotjs,
	SiPostgresql,
	SiPostgresqlHex,
	SiPython,
	SiPythonHex,
	SiReact,
	SiReactHex,
	SiRedis,
	SiRedisHex,
	SiRedux,
	SiReduxHex,
	SiShadcnui,
	SiSupabase,
	SiSupabaseHex,
	SiSwagger,
	SiSwaggerHex,
	SiTailwindcss,
	SiTailwindcssHex,
	SiTypescript,
	SiTypescriptHex,
	SiVuedotjs,
	SiVuedotjsHex,
} from '@icons-pack/react-simple-icons';

const TechStackList = [
	{
		label: 'JavaScript',
		url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
		icon: SiJavascript,
		color: SiJavascriptHex,
	},
	{
		label: 'TypeScript',
		url: 'https://www.typescriptlang.org/',
		icon: SiTypescript,
		color: SiTypescriptHex,
	},
	{
		label: 'Pyhton',
		url: 'https://www.python.org/',
		icon: SiPython,
		color: SiPythonHex,
	},
	{
		label: 'Go',
		url: 'https://golang.org/',
		icon: SiGo,
		color: SiGoHex,
	},
	{
		label: 'Alpine.js',
		url: 'https://alpinejs.dev/',
		icon: SiAlpinedotjs,
		color: SiAlpinedotjsHex,
	},
	{
		label: 'React',
		url: 'https://reactjs.org/',
		icon: SiReact,
		color: SiReactHex,
	},
	{
		label: 'Vue.js',
		url: 'https://vuejs.org/',
		icon: SiVuedotjs,
		color: SiVuedotjsHex,
	},
	{
		label: 'Next.js',
		url: 'https://nextjs.org/',
		icon: SiNextdotjs,
		color: 'fill-neutral-500 group-hover:fill-black dark:group-hover:fill-white',
		border: `hover:border-black/50 dark:hover:border-white/50`,
		customColor: true,
	},
	{
		label: 'Express.js',
		url: 'https://expressjs.com/',
		icon: SiExpress,
		color: 'fill-neutral-500 group-hover:fill-black dark:group-hover:fill-white',
		border: `hover:border-black/50 dark:hover:border-white/50`,
		customColor: true,
	},
	{
		label: 'NestJS',
		url: 'https://nestjs.com/',
		icon: SiNestjs,
		color: SiNestjsHex,
	},
	{
		label: 'Flask',
		url: 'https://flask.palletsprojects.com/',
		icon: SiFlask,
		color: SiFlaskHex,
	},
	{
		label: 'Django',
		url: 'https://www.djangoproject.com/',
		icon: SiDjango,
		color: SiDjangoHex,
	},
	{
		label: 'Tailwind CSS',
		url: 'https://tailwindcss.com/',
		icon: SiTailwindcss,
		color: SiTailwindcssHex,
	},
	{
		label: 'Shadcn UI',
		url: 'https://ui.shadcn.com/',
		icon: SiShadcnui,
		color: 'fill-neutral-500 group-hover:fill-black dark:group-hover:fill-white',
		border: `hover:border-black/50 dark:hover:border-white/50`,
		customColor: true,
	},
	{
		label: 'Ant Design',
		url: 'https://ant.design/',
		icon: SiAntdesign,
		color: SiAntdesignHex,
	},
	{
		label: 'Material UI',
		url: 'https://mui.com/',
		icon: SiMui,
		color: SiMuiHex,
	},
	{
		label: 'Chakra UI',
		url: 'https://chakra-ui.com/',
		icon: SiChakraui,
		color: SiChakrauiHex,
	},
	{
		label: 'PostgreSQL',
		url: 'https://www.postgresql.org/',
		icon: SiPostgresql,
		color: SiPostgresqlHex,
	},
	{
		label: 'MongoDB',
		url: 'https://www.mongodb.com/',
		icon: SiMongodb,
		color: SiMongodbHex,
	},
	{
		label: 'Redis',
		url: 'https://redis.io/',
		icon: SiRedis,
		color: SiRedisHex,
	},
	{
		label: 'Firebase',
		url: 'https://firebase.google.com/',
		icon: SiFirebase,
		color: SiFirebaseHex,
	},
	{
		label: 'Supabase',
		url: 'https://supabase.com/',
		icon: SiSupabase,
		color: SiSupabaseHex,
	},
	{
		label: 'GraphQL',
		url: 'https://graphql.org/',
		icon: SiGraphql,
		color: SiGraphqlHex,
	},
	{
		label: 'Docker',
		url: 'https://www.docker.com/',
		icon: SiDocker,
		color: SiDockerHex,
	},
	{
		label: 'Linux',
		url: 'https://www.linux.org/',
		icon: SiLinux,
		color: SiLinuxHex,
	},
	{
		label: 'Swagger',
		url: 'https://swagger.io/',
		icon: SiSwagger,
		color: SiSwaggerHex,
	},
	{
		label: 'Redux',
		url: 'https://redux.js.org/',
		icon: SiRedux,
		color: SiReduxHex,
	},
] as const satisfies readonly ITechStack[];

type TechStackLabel = (typeof TechStackList)[number]['label'];
type SelectedTechStack<T extends TechStackLabel> = Extract<(typeof TechStackList)[number], { label: T }>;

export function getTechStack<T extends TechStackLabel>(keys: T[]): SelectedTechStack<T>[] {
	return TechStackList.filter((tech): tech is SelectedTechStack<T> => (keys as readonly string[]).includes(tech.label));
}
