[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["cd ../.. && bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun build src/index.ts --outdir dist --target bun --minify"]

[start]
cmd = "bun run dist/index.js"
